services:
  collabreef-nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-runtime
    image: collabreef/collabreef-nginx:local
    container_name: collabreef-nginx
    ports:
      - "80:80"
    depends_on:
      - collabreef-api
      - collabreef-collab
    restart: unless-stopped

  collabreef-collab:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-runtime
    image: collabreef/collabreef:local
    container_name: collabreef-collab
    command: ["node", "collab/src/index.js"]
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - PORT=3000
      - DB_DRIVER=sqlite3
      - DB_DSN=/usr/local/app/bin/collabreef.db
      - APP_SECRET=${APP_SECRET}
    restart: unless-stopped

  collabreef-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-runtime
    image: collabreef/collabreef:local
    container_name: collabreef-api
    command: ["./api"]
    volumes:
      - "./bin:/usr/local/app/bin"
    environment:
      - PORT=8080
      - DB_DRIVER=sqlite3
      - DB_DSN=/usr/local/app/bin/collabreef.db
      - APP_DISABLE_SIGNUP=${APP_DISABLE_SIGNUP}
      - APP_SECRET=${APP_SECRET}
    depends_on:
      collabreef-collab:
        condition: service_started
    restart: unless-stopped
